/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewsItemDTO = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'sourceUrl' : IDL.Text,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'publicationDate' : IDL.Text,
  'category' : IDL.Text,
});
export const NewsCategory = IDL.Variant({
  'movie' : IDL.Null,
  'political' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const News = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'expiresAt' : Time,
  'imageData' : IDL.Opt(IDL.Text),
  'fullContent' : IDL.Text,
  'createdAt' : Time,
  'sourceUrl' : IDL.Text,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'publicationDate' : IDL.Text,
  'category' : NewsCategory,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'articleId' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LiveStatus = IDL.Record({
  'startedAt' : IDL.Opt(Time),
  'isLive' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBulkNews' : IDL.Func([IDL.Vec(NewsItemDTO)], [], []),
  'addNews' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        NewsCategory,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteNews' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Nat], [], []),
  'fetchAndReloadAllNews' : IDL.Func([], [], []),
  'fetchSpecificSource' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLiveStatus' : IDL.Func([], [LiveStatus], ['query']),
  'getNewsByCategory' : IDL.Func([NewsCategory], [IDL.Vec(News)], ['query']),
  'getNewsById' : IDL.Func([IDL.Text], [News], ['query']),
  'getRecentReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getReviewsByArticleId' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isConnected' : IDL.Func([], [IDL.Bool], ['query']),
  'purgeExpiredArticles' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleLiveStatus' : IDL.Func([], [LiveStatus], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewsItemDTO = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'sourceUrl' : IDL.Text,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'publicationDate' : IDL.Text,
    'category' : IDL.Text,
  });
  const NewsCategory = IDL.Variant({
    'movie' : IDL.Null,
    'political' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const News = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'expiresAt' : Time,
    'imageData' : IDL.Opt(IDL.Text),
    'fullContent' : IDL.Text,
    'createdAt' : Time,
    'sourceUrl' : IDL.Text,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'publicationDate' : IDL.Text,
    'category' : NewsCategory,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'articleId' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LiveStatus = IDL.Record({
    'startedAt' : IDL.Opt(Time),
    'isLive' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBulkNews' : IDL.Func([IDL.Vec(NewsItemDTO)], [], []),
    'addNews' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          NewsCategory,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteNews' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Nat], [], []),
    'fetchAndReloadAllNews' : IDL.Func([], [], []),
    'fetchSpecificSource' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLiveStatus' : IDL.Func([], [LiveStatus], ['query']),
    'getNewsByCategory' : IDL.Func([NewsCategory], [IDL.Vec(News)], ['query']),
    'getNewsById' : IDL.Func([IDL.Text], [News], ['query']),
    'getRecentReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getReviewsByArticleId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isConnected' : IDL.Func([], [IDL.Bool], ['query']),
    'purgeExpiredArticles' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleLiveStatus' : IDL.Func([], [LiveStatus], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };