/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface News {
  'id' : string,
  'title' : string,
  'expiresAt' : Time,
  'fullContent' : string,
  'author' : string,
  'summary' : string,
  'imageUrl' : [] | [string],
  'publicationDate' : string,
  'category' : NewsCategory,
}
export type NewsCategory = { 'movie' : null } |
  { 'political' : null };
export interface Review {
  'id' : bigint,
  'createdAt' : Time,
  'reviewText' : string,
  'reviewerName' : string,
  'articleId' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNews' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      NewsCategory,
      string,
      string,
      [] | [string],
    ],
    undefined
  >,
  'addReview' : ActorMethod<[string, string, bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteNews' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[bigint], undefined>,
  'getAllNews' : ActorMethod<[], Array<News>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNewsByCategory' : ActorMethod<[NewsCategory], Array<News>>,
  'getNewsById' : ActorMethod<[string], News>,
  'getReviewsByArticleId' : ActorMethod<[string], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isConnected' : ActorMethod<[], boolean>,
  'purgeExpiredArticles' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];