/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface News {
  'id' : string,
  'title' : string,
  'fullContent' : string,
  'author' : string,
  'summary' : string,
  'imageUrl' : [] | [string],
  'publicationDate' : string,
  'category' : NewsCategory,
}
export type NewsCategory = { 'movie' : null } |
  { 'political' : null };
export interface _SERVICE {
  'addNews' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      NewsCategory,
      string,
      string,
      [] | [string],
    ],
    undefined
  >,
  'getAllNews' : ActorMethod<[], Array<News>>,
  'getNewsByCategory' : ActorMethod<[NewsCategory], Array<News>>,
  'getNewsById' : ActorMethod<[string], News>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];