/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewsCategory = IDL.Variant({
  'movie' : IDL.Null,
  'political' : IDL.Null,
});
export const News = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'fullContent' : IDL.Text,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'publicationDate' : IDL.Text,
  'category' : NewsCategory,
});

export const idlService = IDL.Service({
  'addNews' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        NewsCategory,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'getAllNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
  'getNewsByCategory' : IDL.Func([NewsCategory], [IDL.Vec(News)], ['query']),
  'getNewsById' : IDL.Func([IDL.Text], [News], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewsCategory = IDL.Variant({
    'movie' : IDL.Null,
    'political' : IDL.Null,
  });
  const News = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'fullContent' : IDL.Text,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'publicationDate' : IDL.Text,
    'category' : NewsCategory,
  });
  
  return IDL.Service({
    'addNews' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          NewsCategory,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'getAllNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
    'getNewsByCategory' : IDL.Func([NewsCategory], [IDL.Vec(News)], ['query']),
    'getNewsById' : IDL.Func([IDL.Text], [News], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };