/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LiveStatus { 'startedAt' : [] | [Time], 'isLive' : boolean }
export interface News {
  'id' : string,
  'title' : string,
  'expiresAt' : Time,
  'imageData' : [] | [string],
  'fullContent' : string,
  'createdAt' : Time,
  'sourceUrl' : string,
  'author' : string,
  'summary' : string,
  'publicationDate' : string,
  'category' : NewsCategory,
}
export type NewsCategory = { 'movie' : null } |
  { 'political' : null };
export interface NewsItemDTO {
  'title' : string,
  'content' : string,
  'sourceUrl' : string,
  'author' : string,
  'summary' : string,
  'publicationDate' : string,
  'category' : string,
}
export interface Review {
  'id' : bigint,
  'createdAt' : Time,
  'reviewText' : string,
  'reviewerName' : string,
  'articleId' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBulkNews' : ActorMethod<[Array<NewsItemDTO>], undefined>,
  'addNews' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      NewsCategory,
      string,
      string,
      [] | [string],
      string,
    ],
    undefined
  >,
  'addReview' : ActorMethod<[string, string, bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteNews' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[bigint], undefined>,
  'fetchAndReloadAllNews' : ActorMethod<[], undefined>,
  'fetchSpecificSource' : ActorMethod<[string], string>,
  'getAllNews' : ActorMethod<[], Array<News>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLiveStatus' : ActorMethod<[], LiveStatus>,
  'getNewsByCategory' : ActorMethod<[NewsCategory], Array<News>>,
  'getNewsById' : ActorMethod<[string], News>,
  'getRecentReviews' : ActorMethod<[bigint], Array<Review>>,
  'getReviewsByArticleId' : ActorMethod<[string], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isConnected' : ActorMethod<[], boolean>,
  'purgeExpiredArticles' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleLiveStatus' : ActorMethod<[], LiveStatus>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];